### ISSUE TITLE
Experiencing Error: object 'LIB' not found

### ISSUE THREAD

**Issue by alaneng-zz** [ramnathv/rChartsShiny#2]
Hi there,

Awesome package -- I wanted to reproduce the example in Shiny with the code for this example: http://ramnathv.github.io/rChartsShiny/

Running the code in global.R and subsequently storing ui.R and server.R in a folder, I executed runApp and had this error returned:

> runApp(".../rchart/")

Listening on port 8100
Error in addResourcePath(LIB$name, LIB$url) : object 'LIB' not found

I've Googled this error but couldn't find a solution. I did not edit any code whatsoever, I simply tried to reproduce the example. Could you help me out with this error?

Thanks!

Quick edit: I'm using R version 2.15.3 (2013-03-01) on OS X

**Comment by ramnathv** [comment]
The application broke due to some changes in rCharts. I just pushed a new version of rChartsShiny that should be compatible with the latest version of rCharts. Can you try again? 

Just so you know, the entire app is included [here](https://github.com/ramnathv/rChartsShiny/tree/gh-pages/rChartOECD) in the repo. So you don't need to do any copy paste. Just download the repo, unzip it, change directory and do `runApp('rChartOECD')` and you should have a shiny app up and running.

Let me know if you face further issues.

**Comment by alaneng-zz** [comment]
Fix worked! Thank you!

**Comment by ramnathv** [comment]
You are welcome!
